version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    environment:
      DB_DSN: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./go:/app
    ports:
      - "8080:8080"

  #web:
  #  build:
  #    context: .
  #    dockerfile: docker/next/Dockerfile
  #  environment:
  #    NEXT_PUBLIC_API_URL: http://localhost:8080
  #  depends_on:
  #    - api
  #  volumes:
  #    - ./next:/app
  #  ports:
  #    - "3000:3000"

volumes:
  db-data: